const mapaLogos = {
  "ANGELO FALCONI": "logos/ANGELO FALCONI.jpg",
  "FOOSE": "logos/FOOSE.png",
  "GAME DAY": "logos/GAME DAY.png",
  "GATTIZONI": "logos/GATTIZONI.png",
  "GEORGE": "logos/GEORGE.jpg",
  "ICE LOOK SOL": "logos/ICE LOOK SOL.jpg",
  "JEAN DE PARIS": "logos/JEAN DE PARIS.jpg",
  "JORGIO": "logos/JORGIO.png",
  "LACROSSE SOL": "logos/LACROSSE SOL.jpg",
  "LE GIRO": "logos/LE GIRO.png",
  "LENTE Y ANTIPARRA DE SEGURIDAD": "logos/LENTE Y ANTIPARRA DE SEGURIDAD.jpg",
  "LINEA VIGO SOBRELENTE": "logos/LINEA VIGO SOBRELENTE.png",
  "LINEA VIGO": "logos/LINEA VIGO.png",
  "LUXOR SOBRELENTE": "logos/LUXOR SOBRELENTE.png",
  "LUXOR": "logos/LUXOR.png",
  "MAXCOME": "logos/MAXCOME.jpg",
  "MOODKIDS SOBRELENTE": "logos/MOODKIDS SOBRELENTE.jpg",
  "MOODKIDS": "logos/MOODKIDS.jpg",
  "POLO": "logos/POLO.jpg",
  "SILMO SOBRELENTE": "logos/SILMO SOBRELENTE.jpg",
  "SILMO SOL": "logos/SILMO SOL.jpg",
  "SILMO ÓPTICO": "logos/SILMO ÓPTICO.jpg",
  "SILMO": "logos/SILMO.jpg",
  "VESPA DEPORTIVO": "logos/VESPA DEPORTIVO.png",
  "VESPA KIDS SOL": "logos/VESPA KIDS SOL.png",
  "VESPA KIDS": "logos/VESPA KIDS.png",
  "VESPA PEBAX KIDS": "logos/VESPA PEBAX KIDS.png",
  "VESPA SOL": "logos/VESPA SOL.png",
  "VESPA": "logos/VESPA.png"
};